version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/frontend:/usr/share/nginx/html

  api:
    build:
      context: ./backend
      args:
        service: api
    image: api
    container_name: api
    networks:
      - docker
    expose:
      - 6060
    restart: unless-stopped

networks:
  docker: